export interface StriverProblem {
  id: string;
  step: string;
  stepNum: number;
  topic: string;
  title: string;
  difficulty: "Easy" | "Medium" | "Hard";
  leetcodeUrl: string;
  companies: string[];
  optimalComplexity: { time: string; space: string };
  keyIdea: string;
}

export const STRIVER_STEPS = [
  { stepNum: 1, name: "Step 1: Basics & Hashing" },
  { stepNum: 2, name: "Step 2: Arrays (Easy to Hard)" },
  { stepNum: 3, name: "Step 3: Binary Search" },
  { stepNum: 4, name: "Step 4: Strings" },
  { stepNum: 5, name: "Step 5: Linked List" },
  { stepNum: 6, name: "Step 6: Recursion & Backtracking" },
  { stepNum: 7, name: "Step 7: Stacks & Queues" },
  { stepNum: 8, name: "Step 8: Sliding Window & Two Pointers" },
  { stepNum: 9, name: "Step 9: Binary Trees & BST" },
  { stepNum: 10, name: "Step 10: Graphs" },
  { stepNum: 11, name: "Step 11: Dynamic Programming (DP)" },
  { stepNum: 12, name: "Step 12: Tries & Bit Manipulation" },
];

export const STRIVER_FULL_PROBLEMS: StriverProblem[] = [
  // Step 1: Basics & Hashing
  {
    id: "hashing-1",
    step: "Step 1: Basics & Hashing",
    stepNum: 1,
    topic: "Hashing",
    title: "Two Sum",
    difficulty: "Easy",
    leetcodeUrl: "https://leetcode.com/problems/two-sum/",
    companies: ["Google", "Amazon", "Microsoft", "Meta"],
    optimalComplexity: { time: "O(N)", space: "O(N)" },
    keyIdea: "Use a HashMap to store target - nums[i] index while iterating.",
  },
  {
    id: "hashing-2",
    step: "Step 1: Basics & Hashing",
    stepNum: 1,
    topic: "Hashing",
    title: "Count Frequencies of Elements in Array",
    difficulty: "Easy",
    leetcodeUrl: "https://leetcode.com/problems/frequency-of-the-most-frequent-element/",
    companies: ["Amazon", "TCS Digital", "Accenture"],
    optimalComplexity: { time: "O(N)", space: "O(N)" },
    keyIdea: "Store frequency counts in an unordered_map or frequency array.",
  },
  {
    id: "hashing-3",
    step: "Step 1: Basics & Hashing",
    stepNum: 1,
    topic: "Hashing",
    title: "Longest Consecutive Sequence in an Array",
    difficulty: "Medium",
    leetcodeUrl: "https://leetcode.com/problems/longest-consecutive-sequence/",
    companies: ["Google", "Amazon", "Microsoft", "Adobe"],
    optimalComplexity: { time: "O(N)", space: "O(N)" },
    keyIdea: "Put elements in an unordered_set. Only count sequence if (num - 1) is NOT in set.",
  },
  {
    id: "hashing-4",
    step: "Step 1: Basics & Hashing",
    stepNum: 1,
    topic: "Hashing",
    title: "Longest Subarray with Sum K",
    difficulty: "Medium",
    leetcodeUrl: "https://leetcode.com/problems/subarray-sum-equals-k/",
    companies: ["Amazon", "Uber", "Flipkart", "Goldman Sachs"],
    optimalComplexity: { time: "O(N)", space: "O(N)" },
    keyIdea: "Maintain running prefix sum in a map. Check if (prefixSum - K) was previously seen.",
  },

  // Step 2: Arrays
  {
    id: "arr-1",
    step: "Step 2: Arrays (Easy to Hard)",
    stepNum: 2,
    topic: "Arrays",
    title: "Kadane's Algorithm: Maximum Subarray Sum",
    difficulty: "Medium",
    leetcodeUrl: "https://leetcode.com/problems/maximum-subarray/",
    companies: ["Amazon", "Google", "Microsoft", "LinkedIn"],
    optimalComplexity: { time: "O(N)", space: "O(1)" },
    keyIdea: "Maintain running sum; if sum drops below 0, reset sum to 0. Track overall max.",
  },
  {
    id: "arr-2",
    step: "Step 2: Arrays (Easy to Hard)",
    stepNum: 2,
    topic: "Arrays",
    title: "Sort an Array of 0s, 1s, and 2s (Dutch National Flag)",
    difficulty: "Medium",
    leetcodeUrl: "https://leetcode.com/problems/sort-colors/",
    companies: ["Microsoft", "Amazon", "Meta", "Adobe"],
    optimalComplexity: { time: "O(N)", space: "O(1)" },
    keyIdea: "Use 3 pointers (low, mid, high). Swap nums[mid] with low for 0s and high for 2s.",
  },
  {
    id: "arr-3",
    step: "Step 2: Arrays (Easy to Hard)",
    stepNum: 2,
    topic: "Arrays",
    title: "Majority Element (> N/2 times) - Moore's Voting",
    difficulty: "Easy",
    leetcodeUrl: "https://leetcode.com/problems/majority-element/",
    companies: ["Google", "Amazon", "Microsoft"],
    optimalComplexity: { time: "O(N)", space: "O(1)" },
    keyIdea: "Maintain candidate and count. If count == 0, choose new candidate.",
  },
  {
    id: "arr-4",
    step: "Step 2: Arrays (Easy to Hard)",
    stepNum: 2,
    topic: "Arrays",
    title: "Next Permutation",
    difficulty: "Medium",
    leetcodeUrl: "https://leetcode.com/problems/next-permutation/",
    companies: ["Google", "Amazon", "Meta", "Directi"],
    optimalComplexity: { time: "O(N)", space: "O(1)" },
    keyIdea: "Find breakpoint nums[i] < nums[i+1]. Swap with next greater and reverse right part.",
  },
  {
    id: "arr-5",
    step: "Step 2: Arrays (Easy to Hard)",
    stepNum: 2,
    topic: "Arrays",
    title: "3Sum: Find all Unique Triplets that sum to 0",
    difficulty: "Medium",
    leetcodeUrl: "https://leetcode.com/problems/3sum/",
    companies: ["Meta", "Amazon", "Microsoft", "Apple"],
    optimalComplexity: { time: "O(N^2)", space: "O(1) aux" },
    keyIdea: "Sort array, iterate fixed first element, and use 2 pointers for the remaining pair.",
  },
  {
    id: "arr-6",
    step: "Step 2: Arrays (Easy to Hard)",
    stepNum: 2,
    topic: "Arrays",
    title: "Trapping Rain Water",
    difficulty: "Hard",
    leetcodeUrl: "https://leetcode.com/problems/trapping-rain-water/",
    companies: ["Google", "Amazon", "Goldman Sachs", "Bloomberg"],
    optimalComplexity: { time: "O(N)", space: "O(1)" },
    keyIdea: "Two pointers from left & right tracking leftMax and rightMax.",
  },

  // Step 3: Binary Search
  {
    id: "bs-1",
    step: "Step 3: Binary Search",
    stepNum: 3,
    topic: "Binary Search",
    title: "Search in Rotated Sorted Array",
    difficulty: "Medium",
    leetcodeUrl: "https://leetcode.com/problems/search-in-rotated-sorted-array/",
    companies: ["Google", "Microsoft", "Amazon", "Uber"],
    optimalComplexity: { time: "O(log N)", space: "O(1)" },
    keyIdea: "Identify which half is sorted (left or right) and check if target lies in that range.",
  },
  {
    id: "bs-2",
    step: "Step 3: Binary Search",
    stepNum: 3,
    topic: "Binary Search",
    title: "Find Minimum in Rotated Sorted Array",
    difficulty: "Medium",
    leetcodeUrl: "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/",
    companies: ["Microsoft", "Amazon", "Meta"],
    optimalComplexity: { time: "O(log N)", space: "O(1)" },
    keyIdea: "Compare mid with right pointer. If nums[mid] > nums[high], min is in right half.",
  },
  {
    id: "bs-3",
    step: "Step 3: Binary Search",
    stepNum: 3,
    topic: "Binary Search",
    title: "Koko Eating Bananas (BS on Answer)",
    difficulty: "Medium",
    leetcodeUrl: "https://leetcode.com/problems/koko-eating-bananas/",
    companies: ["Google", "Airbnb", "Amazon"],
    optimalComplexity: { time: "O(N * log(max))", space: "O(1)" },
    keyIdea: "Binary search on speed range [1, max(piles)] with helper function checking total hours.",
  },
  {
    id: "bs-4",
    step: "Step 3: Binary Search",
    stepNum: 3,
    topic: "Binary Search",
    title: "Book Allocation Problem / Split Array Largest Sum",
    difficulty: "Hard",
    leetcodeUrl: "https://leetcode.com/problems/split-array-largest-sum/",
    companies: ["Google", "Amazon", "Flipkart"],
    optimalComplexity: { time: "O(N * log(sum - max))", space: "O(1)" },
    keyIdea: "Binary search on max capacity [max(nums), sum(nums)]. Check if valid partition exists.",
  },

  // Step 4: Strings
  {
    id: "str-1",
    step: "Step 4: Strings",
    stepNum: 4,
    topic: "Strings",
    title: "Valid Anagram",
    difficulty: "Easy",
    leetcodeUrl: "https://leetcode.com/problems/valid-anagram/",
    companies: ["Amazon", "Bloomberg", "Google"],
    optimalComplexity: { time: "O(N)", space: "O(1)" },
    keyIdea: "Count characters using a 26-size frequency array. Verify all counts return to zero.",
  },
  {
    id: "str-2",
    step: "Step 4: Strings",
    stepNum: 4,
    topic: "Strings",
    title: "Longest Common Prefix",
    difficulty: "Easy",
    leetcodeUrl: "https://leetcode.com/problems/longest-common-prefix/",
    companies: ["Amazon", "Apple", "Adobe"],
    optimalComplexity: { time: "O(N * log N)", space: "O(1)" },
    keyIdea: "Sort strings array, then only compare characters between first and last string.",
  },
  {
    id: "str-3",
    step: "Step 4: Strings",
    stepNum: 4,
    topic: "Strings",
    title: "Longest Palindromic Substring",
    difficulty: "Medium",
    leetcodeUrl: "https://leetcode.com/problems/longest-palindromic-substring/",
    companies: ["Amazon", "Microsoft", "Meta", "Google"],
    optimalComplexity: { time: "O(N^2)", space: "O(1)" },
    keyIdea: "Expand around center for both odd and even length centers.",
  },

  // Step 5: Linked List
  {
    id: "ll-1",
    step: "Step 5: Linked List",
    stepNum: 5,
    topic: "Linked List",
    title: "Reverse a Linked List (Iterative & Recursive)",
    difficulty: "Easy",
    leetcodeUrl: "https://leetcode.com/problems/reverse-linked-list/",
    companies: ["Amazon", "Microsoft", "Google", "Apple"],
    optimalComplexity: { time: "O(N)", space: "O(1)" },
    keyIdea: "Use 3 pointers: prev, curr, next. Point curr.next to prev and shift forward.",
  },
  {
    id: "ll-2",
    step: "Step 5: Linked List",
    stepNum: 5,
    topic: "Linked List",
    title: "Detect a Loop in Linked List (Floyd's Tortoise & Hare)",
    difficulty: "Easy",
    leetcodeUrl: "https://leetcode.com/problems/linked-list-cycle/",
    companies: ["Amazon", "Microsoft", "Meta"],
    optimalComplexity: { time: "O(N)", space: "O(1)" },
    keyIdea: "Slow pointer moves 1 step, fast pointer moves 2 steps. If they meet, cycle exists.",
  },
  {
    id: "ll-3",
    step: "Step 5: Linked List",
    stepNum: 5,
    topic: "Linked List",
    title: "LRU Cache Design",
    difficulty: "Medium",
    leetcodeUrl: "https://leetcode.com/problems/lru-cache/",
    companies: ["Amazon", "Google", "Microsoft", "Meta", "Uber"],
    optimalComplexity: { time: "O(1) get & put", space: "O(capacity)" },
    keyIdea: "Doubly Linked List + HashMap mapping key to DLL node pointer for O(1) operations.",
  },

  // Step 6: Recursion & Backtracking
  {
    id: "rec-1",
    step: "Step 6: Recursion & Backtracking",
    stepNum: 6,
    topic: "Recursion",
    title: "Combination Sum (Pick / Not Pick)",
    difficulty: "Medium",
    leetcodeUrl: "https://leetcode.com/problems/combination-sum/",
    companies: ["Amazon", "Meta", "Google"],
    optimalComplexity: { time: "O(2^t * k)", space: "O(k)" },
    keyIdea: "Pick candidate multiple times or skip to next index when target is exceeded.",
  },
  {
    id: "rec-2",
    step: "Step 6: Recursion & Backtracking",
    stepNum: 6,
    topic: "Recursion",
    title: "N-Queens Problem",
    difficulty: "Hard",
    leetcodeUrl: "https://leetcode.com/problems/n-queens/",
    companies: ["Microsoft", "Google", "Amazon"],
    optimalComplexity: { time: "O(N!)", space: "O(N)" },
    keyIdea: "Backtracking with hash sets for left row, upper diagonal (row+col), and lower diagonal (row-col).",
  },

  // Step 7: Stacks & Queues
  {
    id: "stk-1",
    step: "Step 7: Stacks & Queues",
    stepNum: 7,
    topic: "Stacks & Queues",
    title: "Next Greater Element I & II",
    difficulty: "Medium",
    leetcodeUrl: "https://leetcode.com/problems/next-greater-element-i/",
    companies: ["Amazon", "Microsoft", "Meta"],
    optimalComplexity: { time: "O(N)", space: "O(N)" },
    keyIdea: "Monotonic decreasing stack. Pop smaller elements before pushing current.",
  },
  {
    id: "stk-2",
    step: "Step 7: Stacks & Queues",
    stepNum: 7,
    topic: "Stacks & Queues",
    title: "Largest Rectangle in Histogram",
    difficulty: "Hard",
    leetcodeUrl: "https://leetcode.com/problems/largest-rectangle-in-histogram/",
    companies: ["Google", "Amazon", "Microsoft", "Meta"],
    optimalComplexity: { time: "O(N)", space: "O(N)" },
    keyIdea: "Single pass monotonic stack finding previous smaller and next smaller boundaries.",
  },

  // Step 8: Sliding Window
  {
    id: "sw-1",
    step: "Step 8: Sliding Window & Two Pointers",
    stepNum: 8,
    topic: "Sliding Window",
    title: "Longest Substring Without Repeating Characters",
    difficulty: "Medium",
    leetcodeUrl: "https://leetcode.com/problems/longest-substring-without-repeating-characters/",
    companies: ["Google", "Amazon", "Meta", "Bloomberg"],
    optimalComplexity: { time: "O(N)", space: "O(min(N, 256))" },
    keyIdea: "Sliding window with map storing last seen index of each character to skip left bounds.",
  },
  {
    id: "sw-2",
    step: "Step 8: Sliding Window & Two Pointers",
    stepNum: 8,
    topic: "Sliding Window",
    title: "Max Consecutive Ones III",
    difficulty: "Medium",
    leetcodeUrl: "https://leetcode.com/problems/max-consecutive-ones-iii/",
    companies: ["Meta", "Google", "Microsoft"],
    optimalComplexity: { time: "O(N)", space: "O(1)" },
    keyIdea: "Sliding window allowing at most K zeroes. Shrink left pointer when zeroCount > K.",
  },

  // Step 9: Binary Trees & BST
  {
    id: "tree-1",
    step: "Step 9: Binary Trees & BST",
    stepNum: 9,
    topic: "Binary Trees",
    title: "Lowest Common Ancestor (LCA) in Binary Tree",
    difficulty: "Medium",
    leetcodeUrl: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/",
    companies: ["Meta", "Amazon", "Microsoft", "Google"],
    optimalComplexity: { time: "O(N)", space: "O(H)" },
    keyIdea: "If root == p or root == q, return root. If both left and right return non-null, root is LCA.",
  },
  {
    id: "tree-2",
    step: "Step 9: Binary Trees & BST",
    stepNum: 9,
    topic: "Binary Trees",
    title: "Diameter of Binary Tree",
    difficulty: "Easy",
    leetcodeUrl: "https://leetcode.com/problems/diameter-of-binary-tree/",
    companies: ["Meta", "Amazon", "Google"],
    optimalComplexity: { time: "O(N)", space: "O(H)" },
    keyIdea: "Calculate height of left and right subtree at each node; update maxDiameter = left + right.",
  },
  {
    id: "tree-3",
    step: "Step 9: Binary Trees & BST",
    stepNum: 9,
    topic: "Binary Trees",
    title: "Validate Binary Search Tree (BST)",
    difficulty: "Medium",
    leetcodeUrl: "https://leetcode.com/problems/validate-binary-search-tree/",
    companies: ["Amazon", "Microsoft", "Google", "Meta"],
    optimalComplexity: { time: "O(N)", space: "O(H)" },
    keyIdea: "Pass valid (minVal, maxVal) range bounds down to every recursive node call.",
  },

  // Step 10: Graphs
  {
    id: "graph-1",
    step: "Step 10: Graphs",
    stepNum: 10,
    topic: "Graphs",
    title: "Number of Islands (BFS / DFS)",
    difficulty: "Medium",
    leetcodeUrl: "https://leetcode.com/problems/number-of-islands/",
    companies: ["Amazon", "Google", "Microsoft", "Meta", "Bloomberg"],
    optimalComplexity: { time: "O(M * N)", space: "O(M * N)" },
    keyIdea: "Traverse grid; when '1' is found, increment island count and DFS/BFS to sink connected '1's.",
  },
  {
    id: "graph-2",
    step: "Step 10: Graphs",
    stepNum: 10,
    topic: "Graphs",
    title: "Course Schedule I & II (Topological Sort / Kahn's Algo)",
    difficulty: "Medium",
    leetcodeUrl: "https://leetcode.com/problems/course-schedule/",
    companies: ["Amazon", "Google", "Microsoft", "Uber"],
    optimalComplexity: { time: "O(V + E)", space: "O(V + E)" },
    keyIdea: "Calculate in-degrees. Use Queue with in-degree == 0. If visited count == V, no cycle exists.",
  },
  {
    id: "graph-3",
    step: "Step 10: Graphs",
    stepNum: 10,
    topic: "Graphs",
    title: "Dijkstra's Shortest Path Algorithm",
    difficulty: "Medium",
    leetcodeUrl: "https://leetcode.com/problems/network-delay-time/",
    companies: ["Google", "Amazon", "Microsoft"],
    optimalComplexity: { time: "O(E * log V)", space: "O(V + E)" },
    keyIdea: "Min-Heap storing (distance, node). Greedily relax outgoing edges with smaller distance.",
  },

  // Step 11: Dynamic Programming (DP)
  {
    id: "dp-1",
    step: "Step 11: Dynamic Programming (DP)",
    stepNum: 11,
    topic: "Dynamic Programming",
    title: "Climbing Stairs / Fibonacci Pattern",
    difficulty: "Easy",
    leetcodeUrl: "https://leetcode.com/problems/climbing-stairs/",
    companies: ["Amazon", "Google", "Microsoft"],
    optimalComplexity: { time: "O(N)", space: "O(1)" },
    keyIdea: "dp[i] = dp[i-1] + dp[i-2]. Optimize space with two state variables prev & prev2.",
  },
  {
    id: "dp-2",
    step: "Step 11: Dynamic Programming (DP)",
    stepNum: 11,
    topic: "Dynamic Programming",
    title: "0/1 Knapsack Problem",
    difficulty: "Medium",
    leetcodeUrl: "https://leetcode.com/problems/partition-equal-subset-sum/",
    companies: ["Amazon", "Flipkart", "Microsoft"],
    optimalComplexity: { time: "O(N * W)", space: "O(W)" },
    keyIdea: "Pick/Not-pick 1D array space optimization traversing backwards from W to wt[i].",
  },
  {
    id: "dp-3",
    step: "Step 11: Dynamic Programming (DP)",
    stepNum: 11,
    topic: "Dynamic Programming",
    title: "Longest Common Subsequence (LCS)",
    difficulty: "Medium",
    leetcodeUrl: "https://leetcode.com/problems/longest-common-subsequence/",
    companies: ["Amazon", "Microsoft", "Google"],
    optimalComplexity: { time: "O(N * M)", space: "O(M)" },
    keyIdea: "If s1[i] == s2[j] -> 1 + dp[i-1][j-1], else max(dp[i-1][j], dp[i][j-1]).",
  },
  {
    id: "dp-4",
    step: "Step 11: Dynamic Programming (DP)",
    stepNum: 11,
    topic: "Dynamic Programming",
    title: "Edit Distance",
    difficulty: "Hard",
    leetcodeUrl: "https://leetcode.com/problems/edit-distance/",
    companies: ["Google", "Amazon", "Microsoft", "Meta"],
    optimalComplexity: { time: "O(N * M)", space: "O(M)" },
    keyIdea: "Min operations: 1 + min(insert, delete, replace) when characters do not match.",
  },

  // Step 12: Tries & Bit Manipulation
  {
    id: "trie-1",
    step: "Step 12: Tries & Bit Manipulation",
    stepNum: 12,
    topic: "Tries",
    title: "Implement Trie (Prefix Tree)",
    difficulty: "Medium",
    leetcodeUrl: "https://leetcode.com/problems/implement-trie-prefix-tree/",
    companies: ["Google", "Amazon", "Microsoft", "Twitter"],
    optimalComplexity: { time: "O(word length)", space: "O(total characters * 26)" },
    keyIdea: "TrieNode with children array[26] and isEnd boolean flag for O(L) search & insert.",
  },
  {
    id: "bit-1",
    step: "Step 12: Tries & Bit Manipulation",
    stepNum: 12,
    topic: "Bit Manipulation",
    title: "Single Number (Every element appears twice except one)",
    difficulty: "Easy",
    leetcodeUrl: "https://leetcode.com/problems/single-number/",
    companies: ["Amazon", "Google", "Meta"],
    optimalComplexity: { time: "O(N)", space: "O(1)" },
    keyIdea: "XOR of all elements. a ^ a = 0 and a ^ 0 = a, isolating the single unique element.",
  }
];

export function getStriverProblemOfTheDay(solvedIds: string[] = []): StriverProblem {
  // Find first unsolved problem from Step 2 onwards (or overall)
  const unsolvedFromStep2 = STRIVER_FULL_PROBLEMS.filter(
    (p) => p.stepNum >= 2 && !solvedIds.includes(p.id)
  );

  if (unsolvedFromStep2.length > 0) {
    const dayOfYear = Math.floor((Date.now() - new Date(new Date().getFullYear(), 0, 0).getTime()) / (1000 * 60 * 60 * 24));
    const index = dayOfYear % unsolvedFromStep2.length;
    return unsolvedFromStep2[index];
  }

  // Fallback to any problem
  const dayOfYear = Math.floor((Date.now() - new Date(new Date().getFullYear(), 0, 0).getTime()) / (1000 * 60 * 60 * 24));
  return STRIVER_FULL_PROBLEMS[dayOfYear % STRIVER_FULL_PROBLEMS.length];
}
